config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bookings/index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'static_pages#home'
  resources :users, :only => [:show] do
    resources :orders, :only=> [:index, :show, :new, :create, :destroy] do
      resources :bookings, :only=> [:index]
    end
  end
  get 'manage/index'
  get 'manage/bookings'
  get 'manage/switch'
  get 'static_pages/procedure'
  get 'static_pages/about'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
      can :access, :manage
    else
      cannot :access, :manage
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :order
  validates :restaurant_name, presence: true
  validates :date, presence: true
  validates :member_num, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => 'input your name'}
  validates :email, :presence => {:message => 'input your email address'}
end

app/models/order.rb
require 'date'

class Order < ActiveRecord::Base
  belongs_to :user
  has_many :bookings, dependent: :delete_all
  accepts_nested_attributes_for :bookings, allow_destroy: true

  enum plan_type: {normal: 0, exclusive: 1}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :member_num, presence: true, numericality: { only_integer: true, greater_than: 0 }, if: :exclusive?
  validate :has_bookings, if: :normal?

  def set_date
    start_date = self.bookings.first.date
    end_date = self.bookings.first.date
    self.bookings.each do |booking|
      if start_date > booking.date
        start_date = booking.date
      end
      if end_date < booking.date
        end_date = booking.date
      end
      self.start_date = start_date
      self.end_date = end_date
    end
  end

  def switch
    if self.done
      self.done = false
    else
      self.done = true
    end
  end

  def exclusive?
    plan_type == "exclusive"
  end

  def normal?
    plan_type == "normal"
  end

  def has_bookings
    errors.add(:bookings, "no booking has added") if bookings.empty?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable,:database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :orders

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, :alert => exception.message
  end

  def authenticate_user
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user, only: [:index]
  def index
    @order = Order.find(params[:order_id])
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(params[:inquiry])
    InquiryMailer.received_email(@inquiry).deliver_now
    render :action => 'thanks'
  end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  authorize_resource class: false
  def index
    @orders = Order.all
  end

  def bookings
    @order = Order.find(params[:id])
  end

  def switch
    order = Order.find(params[:id])
    order.switch
    order.save
    redirect_to manage_index_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :index, :destroy]

  def new
    @order = Order.new
    @order.bookings.build
  end

  def create
    @order = Order.new(order_params)
    if !@order.bookings.empty?
      @order.set_date
    end
    if !@order.save
      render :new
    end
  end

  def show
  end

  def index
  end

  def destroy
    Order.destroy(params[:id])
    redirect_to user_orders_path(current_user), notice: "deleted an order"
  end

  private
    def order_params
      params.require(:order).permit(:user_id, :plan_type, :member_num, :start_date, :end_date, bookings_attributes: [:id, :restaurant_name, :member_num, :description, :date, :_destroy])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def procedure
  end

  def about
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]

  def show
    @user = current_user
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.haml
%div.container
  %h1
    = "Bookings for stay during"
    = @order.start_date
    = "~"
    = @order.end_date
  %table.table
    %thead
      %tr
        %th
          restaurant_name
        %th
          number of members
        %th
          date
        %th
          note
    %tbody
      - @order.bookings.each do |booking|
        %tr
          %td
            = booking.restaurant_name
          %td
            = booking.member_num
          %td
            = booking.date
          %td
            = booking.description

app/views/home/show.html.haml
%div.mainImg
  %div.mainPhrase
    Booking local
    %br
    restaurants made easy.
    %br
    Locodine.
%div.container
  %div.infoBox
    %div.leftBox
      %div.address.infoElm
        500 Terry Francois Street,
        %br
        San Francisco, CA 94158  |  1-800-000-0000
      %div.sns.infoElm
        %i.fa.fa-facebook.fa-2x
        %i.fa.fa-twitter.fa-2x
        %i.fa.fa-tripadvisor.fa-2x
        %i.fa.fa-instagram.fa-2x
    %div.rightBox
      %div.mailBox.infoElm
        Join our mailing list
        %br
        Never miss an update

    %div.clear

app/views/inquiry/confirm.html.haml
%div.container
  %h1 Inquiry
  = form_for @inquiry, url: inquiry_thanks_path do |f|
    .form-group
      = f.label :name, "name" , class: "control-label"
      %br
      = @inquiry.name
      = f.hidden_field :name, class: "form-control"
    .form-group
      = f.label :email, "email" , class: "control-label"
      %br
      = @inquiry.email
      = f.hidden_field :email, class: "form-control"
    .form-group
      = f.label :message, "message" , class: "control-label"
      %br
      = @inquiry.message
      = f.hidden_field :message, class: "form-control"
    = f.submit 'confirm', class: "btn btn-primary"

app/views/inquiry/index.html.haml
%div.container
  %h1 Inquiry
  - if @inquiry.errors.any?
    %div.alert.alert-danger{role: 'alert'}
      %ul
        - @inquiry.errors.each do |attr,msg|
          %li
            #{msg}
  %div
    = form_for @inquiry, url: inquiry_confirm_path do |f|
      .form-group
        = f.label :name, "name" , class: "control-label"
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :email, "email" , class: "control-label"
        = f.text_field :email, class: "form-control"
      .form-group
        = f.label :message, "message"  , class: "control-label"
        = f.text_area :message, class: "form-control"
      = f.submit 'submit', class: "btn btn-primary"

app/views/inquiry/thanks.html.haml
%div.container
  %h1
    Inquiry
  %p.followingBox
    Thank You For Your Inquiry!!!

app/views/layouts/_footer.html.haml
%div.container
  %div.infoBox
    %div.leftBox
      %div.address.infoElm
        %br
        %br
      %div.sns.infoElm
        %i.fa.fa-facebook.fa-2x
        %i.fa.fa-twitter.fa-2x
        %i.fa.fa-tripadvisor.fa-2x
        %i.fa.fa-instagram.fa-2x
    %div.rightBox
      %div.mailBox.infoElm
        %br
        %br


    %div.clear
    %div
      Font made from
      %a{href: "http://www.onlinewebfonts.com"}
        oNline Web Fonts
        is licensed by CC BY 3.0

app/views/layouts/_header.html.haml
%div.container
  %div.navbar.navbar-default{role: "navigation"}
    %div.navbar-haeder
      %button.navbar-toggle{type: :button, data: {toggle: "collapse", target: ".navbar-collapse"}}
      %span.sr-only menu
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
      = link_to 'LOCODINE', root_path, class: 'navbar-brand'
    %div.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Booking Procedures', static_pages_procedure_path
        - if user_signed_in?
          %li
            = link_to 'Book Now', new_user_order_path(current_user.id)
        - else
          %li
            = link_to 'Book Now', '#'
        %li
          = link_to 'About', static_pages_about_path
        %li
          = link_to 'Contact US', inquiry_index_path
        - if user_signed_in?
          %li
            = link_to 'My page', current_user
          %li.signup
            = link_to 'Log Out', destroy_user_session_path, method: :delete
        - else
          %li.signup
            = link_to 'Log In', new_user_session_path
          %li.signup
            = link_to 'SIGNUP NOW', new_user_registration_path

app/views/layouts/application.html.haml
%html
%head
  %titleJinnyApp
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
= render partial: "layouts/header"
%div.container
  - if notice
    %p.notice
      = notice
  - if alert
    %p.alert
      = alert
= yield
= render partial: "layouts/footer"

app/views/orders/create.html.haml
%div.container
  %div.bigMessage
    We Have Received The Order

app/views/orders/destroy.html.haml
%h1 Orders#destroy
%p Find me in app/views/orders/destroy.html.haml

app/views/orders/index.html.haml
%div.container
  %h1 Orders
  %table.table
    %thead
      %tr
        %th
          plan type
        %th
          number of members
        %th
          date
        %th
          bookings
        %th

    %tbody
      - current_user.orders.each do |order|
        %tr
          %td
            = order.plan_type
          %td
            = order.member_num
          %td
            = order.start_date
            = "~"
            = order.end_date
          %td
            - if order.plan_type == 'normal'
              = link_to 'show bookings', user_order_bookings_path(user_id: params[:user_id], order_id: order.id)
            - else
              = "-"
          %td
            = button_to "delete", { :action => "destroy", :id => order.id }, data: { confirm: "really delete?"}, :method => :delete, class: "btn btn-danger"

app/views/orders/new.html.haml
%div.container
  %h2
    %strong
      Book Now!!
  - if @order.errors.any?
    %div.alert.alert-danger
      - @order.errors.each do |attr, message|
        %li
          = attr.to_s + ' ' + message

  %ul.nav.nav-tabs
    %li.nav-item.active
      %a.nav-link.bg-primary{href: "#normal", data: {toggle: "tab"}}
        normal plan
    %li.nav-item
      %a.nav-link.bg-primary{href: "#exclusive", data: {toggle: "tab"}}
        exclusive plan

  %div.tab-content
    %div.tab-pane.active{id: "normal"}
      = form_for [current_user, @order] do |f|
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :plan_type, value: "normal"
        = f.nested_fields_for :bookings do |ff|
          .form-group
            = ff.label :restaurant_name, "where to book?" , class: "control-label"
            = ff.text_field :restaurant_name, class: "form-control"
          .form-group
            = ff.label :member_num, "number of member" , class: "control-label"
            = ff.number_field :member_num, class: "form-control"
          .form-group
            = ff.label :description, "note" , class: "control-label"
            = ff.text_area :description, class: "form-control"
          .form-group
            = ff.label :date, "date" , class: "control-label"
            %br
            = ff.datetime_select :date, class: "form-control"
          %div.rightBtn
            = ff.remove_nested_fields_link 'Delete', class: "btn btn-danger"
        %br
        = f.add_nested_fields_link :bookings, 'Add new', class: "btn btn-primary rightBtn"
        %br
        %br
        = f.submit 'submit', class: "btn btn-primary"
    %div.tab-pane{id: "exclusive"}
      = form_for [current_user, @order] do |f|
        .form-group
          = f.label :start_date, "travel period" , class: "control-label"
          %br
          = f.date_select :start_date, class: "form-control"
          = "~"
          = f.date_select :end_date, class: "form-control"
        .form-group
          = f.label :member_num, "number of member" , class: "control-label"
          = f.number_field :member_num, class: "form-control"
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :plan_type, value: "exclusive"
        = f.submit 'submit', class: "btn btn-primary"

app/views/static_pages/about.html.haml
%div.container
  %div
    %span.locodineTitle
      LOCODINE
    %span.titleAttatchment
      Easy. Convenient. Fast.

  %div.preparagraph
    Locodine is an exclusive service provided to help reserve and book high-class restaurants in Tokyo.

  %div.aboutFollowing
    It all started with friends asking to help reserve top-notch restaurants that did not
    take reservations from overseas customers. Japanese culture embodies a strict rule
    against timely promises like reservations - and to top-notch restaurants, time means
    everything. Cancellation after the designated time period results in fees - that are
    more difficult to charge against overseas customers. Only through hotel concierges
    would restaurants take reservations from foreign customers. High quality
    restaurants that required booking months ahead of time were extremely difficult to reserve for.

  %div.aboutFollowing
    Until the creation of Locodine, customers had to go through hotel concierges to book
    restaurants that often resulted in missing reservations and complications. Locodine
    will make the reservation and notify immediately upon success. The whole process is
    speedy and smooth with secure online payment services.

  %div.aboutFollowing
    Locodine makes reservations
    %strong
      easy, convenient,
    and
    %strong
      fast.
    Exclusive members are provided with additional assistance in dining itinerary building.

app/views/static_pages/home.html.haml
%div.mainImg
  %div.mainPhrase
    Booking local
    %br
    restaurants made easy.
    %br
    Locodine.

app/views/static_pages/procedure.html.haml
%div.container
  %h3
    %strong
      Booking Procedures
  %div.discriptions
    Booking procedures are done easy through Locodine
    %ol
      %li
        %strong
          Sign up
        for a membership and fill in an inquiry form with a list of restaurants you would like to
        book during the time of your visit to Tokyo. Please make sure to specify the dates of your visit.
      %li
        %strong
          Pay for your reservation.
        %br
        Each reservation is charged with a 10% service fee and with a cancellation deposit fee prompted
        by each restaurant. Upon cancellation, cancellation deposits will be paid to the individual
        restaurants and are not available for refunds. All payments are made online securely through Paypal.
        For other questions, please
        %span.inlineLink
          = link_to 'contact us.', inquiry_index_path
      %li
        Reservations will be made immediately upon restaurant business hours.
      %li
        Locodine will email a reservation confirmation form to your email.
      %li
        Show up
        %strong
          ON-TIME
        to your reservation and enjoy the amazing meal.

  %div.followingBox
    Customer service in English, Chinese, Korean and Japanese will be available during business hours of 11am - 10pm.

  %div.followingBox
    *For Exclusive Members
    %br
    Exclusive Members are provided with a full assistance to dining itinerary building.

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml

app/views/users/show.html.haml
%div.container
  %aside.col-mid-4
    %section
      %h1
        = @user.name
      %h3
        email:
        = @user.email
      %table.table
        %thead
          %tr
            %th
              plan type
            %th
              number of members
            %th
              date
            %th
              bookings
            %th

        %tbody
          - @user.orders.each do |order|
            %tr
              %td
                = order.plan_type
              %td
                = order.member_num
              %td
                = order.start_date
                = "~"
                = order.end_date
              %td
                - if order.plan_type == 'normal'
                  = link_to 'show bookings', user_order_bookings_path(user_id: @user.id, order_id: order.id)
                - else
                  = "-"
              %td
                = button_to "delete", user_order_path(@user.id,order.id), data: { confirm: "really delete?"}, :method => :delete, class: "btn btn-danger"

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml